services:
  app:
    build: ./docker/php
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./src/laravel/:/var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"

  web:
    image: nginx:1.29.1
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/laravel/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  composer:
    image: composer:2
    container_name: laravel-composer
    working_dir: /app
    volumes:
      - ./src:/app
    entrypoint: ["composer"]

